### ISSUE TITLE
Sumo-bandplot fails with KeyError: <Spin.up: 1>

### ISSUE THREAD

**Issue by JQNG** [SMTG-Bham/sumo#226]
Dear Sumo team,

Sumo-bandplot appears to fail to parse some of my vasprun.xml files when projections is selected while working fine for others. These xml files fail with the following errors:

`Traceback (most recent call last):

  File "/mt/tools/vasp/bin/sumo-bandplot", line 33, in <module>
    sys.exit(load_entry_point('sumo', 'console_scripts', 'sumo-bandplot')())
  File "/mt/sumo/sumo/cli/bandplot.py", line 880, in main
    bandplot(
  File "/mt/sumo/sumo/cli/bandplot.py", line 415, in bandplot
    plt = plotter.get_projected_plot(
  File "/mt/sumo/sumo/plotting/__init__.py", line 58, in wrapper
    return get_plot(*args, **kwargs)
  File "/mt/sumo/sumo/plotting/bs_plotter.py", line 555, in get_projected_plot
    proj = get_projections_by_branches(self.bs, selection, normalise=normalise)
  File "/mt/sumo/sumo/electronic_structure/bandstructure.py", line 68, in get_projections_by_branches
    projections = get_projections(bs, selection, normalise=normalise)
  File "/mt/sumo/sumo/electronic_structure/bandstructure.py", line 179, in get_projections
    proj[spin] += dict_proj[element][orbital][spin]
KeyError: <Spin.up: 1>
`

Normal band structure plotting works fine and sumo-bandstats work correctly too. It is only when projections is selected then the above error appears. LORBIT is verified set as 11. Attached are the relevant vasprun.xml, INCAR and POSCAR files for debugging.

**Comment by JQNG** [comment]
Dear Sumo Team,

I managed to trace the problem. It was my own mistake with the POTCAR that caused the parsing to not work properly. For other users to reference in case they have the same error.

**Comment by ajjackson** [comment]
Ok, thanks for the update. Happy computing!
