### ISSUE TITLE
error plotting band structure

### ISSUE THREAD

**Issue by oisin67** [SMTG-Bham/sumo#236]
Hi. I am trying to plot band structure on SUMO. I have a kpoints file and a vasprun.xml which worked fine for plotting dos yet when I go to plot band structure I get this error. Could anyone explain it to me please?

Traceback (most recent call last):
  File "/home/cmtg/.local/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/home/cmtg/.local/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 886, in main
    bandplot(
  File "/home/cmtg/.local/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 298, in bandplot
    bs = vr.get_band_structure(line_mode=True)
  File "/home/cmtg/.local/lib/python3.8/site-packages/pymatgen/io/vasp/outputs.py", line 958, in get_band_structure
    if "" in kpoint_file.labels:
TypeError: argument of type 'NoneType' is not iterable

**Comment by ajjackson** [comment]
Was the KPOINTS file created using `sumo-kgen`? Does it include the symmetry labels?

**Comment by oisin67** [comment]
I just created a KPOINTS file myself. It looks like this: 

Regular mesh centered at Gamma (better forces)
0
Gamma
12 12 5

that's all I have. That and a vasprun.xml file

**Comment by ajjackson** [comment]
That's not a suitable KPOINTS for a band structure diagram, it's a regular sampling mesh for a DOS.

You need to use `sumo-kgen` to create an appropriate KPOINTS file and run a non-self-consistent calculation using the density from the DOS calculation.

**Comment by ajjackson** [comment]
Hi @oisin67 did you manage to do a full band structure calculation and plot it?
